name: C/C++ CI

on:
  push:
    branches: [ 10-latest ]
  pull_request:
    branches: [ 10-latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
